WDL-OL/IPlug: MidiSynth Class Reference
MidiSynth Class Reference
A monophonic/polyphonic synthesiser base class which can be supplied with a custom voice.
#include <MidiSynth.h>
Classes
struct KeyPressInfo
class Voice
Public Types
enum EATMode { kATModeChannel = 0, kATModePoly, kNumATModes }
enum EPolyMode { kPolyModePoly = 0, kPolyModeLegato, kPolyModeMono, kNumPolyModes }
Public Member Functions
MidiSynth (EPolyMode polyMode=kPolyModePoly, int blockSize=16)
void Reset ()
void SetSampleRateAndBlockSize (double sampleRate, int blockSize)
void SetPolyMode (EPolyMode mode)
void SetATMode (EATMode mode)
void SetNoteOffset (double offset)
Voice * GetVoice (int voiceIdx)
int NVoices () const
void AddVoice (Voice *pVoice)
void AddMidiMsgToQueue (const IMidiMsg &msg)
bool ProcessBlock (sample **inputs, sample **outputs, int nInputs, int nOutputs, int nFrames)
Processes a block of audio samples.
Public Attributes
int mVelocityLUT [128]
int mAfterTouchLUT [128]
Protected Member Functions
virtual double GetAdjustedPitch (int key)
Override this method if you need to implement a tuning table for microtonal support.
Detailed Description
A monophonic/polyphonic synthesiser base class which can be supplied with a custom voice.
Supports different kinds of after touch, pitch bend, velocity and after touch curves, unison (currently monophonic mode only) NOTE: This is not currently particularly efficient, and needs a bit more work to be more generalisable
Definition at line 21 of file MidiSynth.h.
Member Function Documentation
virtual double MidiSynth::GetAdjustedPitch (int key) inline protected virtual
Override this method if you need to implement a tuning table for microtonal support.
Parameters
key The input MIDI pitch of the key pressed
Returns
The adjusted MIDI pitch
Definition at line 185 of file MidiSynth.h.
bool MidiSynth::ProcessBlock (sample ** inputs, sample ** outputs, int nInputs, int nOutputs, int nFrames)
Processes a block of audio samples.
Parameters
inputs Pointer to input Arrays
outputs Pointer to output Arrays
nInputs The number of input channels that contain valid data
nOutputs input channels that contain valid data
nFrames The number of sample frames to process
Returns
true if the synth is silent
Definition at line 22 of file MidiSynth.cpp.
References IMidiMsg::ChannelAfterTouch(), IMidiMsg::ControlChange(), IMidiMsg::NoteNumber(), IMidiMsg::PitchWheel(), IMidiMsg::PolyAfterTouch(), and MidiSynth::Voice::ProcessSamples().
The documentation for this class was generated from the following files:
MidiSynth.h
MidiSynth.cpp